In [22]:
import pandas as pd
import re
import goodtables

In [31]:
df = pd.read_csv('Haushaltsentwurf_2018.csv', sep=';', keep_default_na=False)
df.head()

,OE,Produkt,Teilprodukt,Kostenartengruppe,2018 (Plan),Ertrag/Aufwand,Interne Leist.
0,(61) FB Städtebau,1.100.5.1.1.05 Bebauungsplanung,1.100.5.1.1.05.02 Sonderprojekte räuml.Entwick...,15 Aufwendungen für Sach-/Dienstleistungen,-100000,Aufwand,nein
1,(68) FB Umwelt und Klimaschutz,1.100.5.6.1.03 CO2 Reduzierung,1.100.5.6.1.03.01 CO2 Reduzierung,18 Transferaufwendungen,-75000,Aufwand,nein
2,(61) FB Städtebau,1.100.5.1.1.04 Verkehrsplanung,1.100.5.1.1.04.01 Verkehrsplanung,15 Aufwendungen für Sach-/Dienstleistungen,-60000,Aufwand,nein
3,(61) FB Städtebau,1.100.5.1.1.04 Verkehrsplanung,1.100.5.1.1.04.02 Radverkehr,15 Aufwendungen für Sach-/Dienstleistungen,-50000,Aufwand,nein
4,(61) FB Städtebau,1.100.5.1.1.05 Bebauungsplanung,1.100.5.1.1.05.01 Bebauungsplanung,15 Aufwendungen für Sach-/Dienstleistungen,-70000,Aufwand,nein

In [32]:
# Remove all product IDs.
num_regex = r'(\d+\.?)+\s'
df['Produkt'] = df['Produkt'].replace(regex=num_regex, value='')
df['Teilprodukt'] = df['Teilprodukt'].replace(regex=num_regex, value='')

# Remove OE ID and redundant abbreviation.
oe_num_regex = r'\(?\d+\)?\s'
df['OE'] = df['OE'].replace(regex=oe_num_regex, value='')
df['Kostenartengruppe'] = df['Kostenartengruppe'].replace(regex=oe_num_regex, value='')

# # Remove FB prefix.
df['OE'] = df['OE'].replace(regex=r'^FB\s', value='')


# Add date, to be in accordance with the openspending form requirements.
df['Datum'] = 2018
df.head()

,OE,Produkt,Teilprodukt,Kostenartengruppe,2018 (Plan),Ertrag/Aufwand,Interne Leist.,Datum
0,Städtebau,Bebauungsplanung,Sonderprojekte räuml.Entwickl.planung,Aufwendungen für Sach-/Dienstleistungen,-100000,Aufwand,nein,2018
1,Umwelt und Klimaschutz,COReduzierung,COReduzierung,Transferaufwendungen,-75000,Aufwand,nein,2018
2,Städtebau,Verkehrsplanung,Verkehrsplanung,Aufwendungen für Sach-/Dienstleistungen,-60000,Aufwand,nein,2018
3,Städtebau,Verkehrsplanung,Radverkehr,Aufwendungen für Sach-/Dienstleistungen,-50000,Aufwand,nein,2018
4,Städtebau,Bebauungsplanung,Bebauungsplanung,Aufwendungen für Sach-/Dienstleistungen,-70000,Aufwand,nein,2018

In [33]:
df.drop_duplicates(inplace=True)

In [35]:
df = df.rename(columns={'OE': 'Organisationseinheit', 
                        'Interne Leist.': 'Interne Leistung',
                        '2018 (Plan)': 'Betrag'})
df.head()

,Organisationseinheit,Produkt,Teilprodukt,Kostenartengruppe,Betrag,Ertrag/Aufwand,Interne Leistung,Datum
0,Städtebau,Bebauungsplanung,Sonderprojekte räuml.Entwickl.planung,Aufwendungen für Sach-/Dienstleistungen,-100000,Aufwand,nein,2018
1,Umwelt und Klimaschutz,COReduzierung,COReduzierung,Transferaufwendungen,-75000,Aufwand,nein,2018
2,Städtebau,Verkehrsplanung,Verkehrsplanung,Aufwendungen für Sach-/Dienstleistungen,-60000,Aufwand,nein,2018
3,Städtebau,Verkehrsplanung,Radverkehr,Aufwendungen für Sach-/Dienstleistungen,-50000,Aufwand,nein,2018
4,Städtebau,Bebauungsplanung,Bebauungsplanung,Aufwendungen für Sach-/Dienstleistungen,-70000,Aufwand,nein,2018

In [36]:
save_filename = 'haushalt_clean.csv' 
df.to_csv(save_filename, index=False)

In [37]:
report = goodtables.validate(save_filename, row_limit=20_000)
report

{'error-count': 0,
 'preset': 'table',
 'table-count': 1,
 'tables': [{'encoding': 'utf-8',
   'error-count': 0,
   'errors': [],
   'format': 'csv',
   'headers': ['Organisationseinheit',
    'Produkt',
    'Teilprodukt',
    'Kostenartengruppe',
    'Betrag',
    'Ertrag/Aufwand',
    'Interne Leistung',
    'Datum'],
   'row-count': 14911,
   'schema': None,
   'scheme': 'file',
   'source': 'haushalt_clean.csv',
   'time': 2.074,
   'valid': True}],
 'time': 2.09,
 'valid': True,
 'warnings': []}